name: Update README with Private Repo Stats

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}

      - name: Update README
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          # Fetch private stats
          private_stats=$(curl -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/users/itsanamune)
          
          # Extract relevant data
          public_repos=$(echo $private_stats | jq .public_repos)
          total_repos=$(echo $private_stats | jq .total_private_repos)
          followers=$(echo $private_stats | jq .followers)
          following=$(echo $private_stats | jq .following)
          
          # Update README
          sed -i '/<!-- START_SECTION:stats -->/,/<!-- END_SECTION:stats -->/c\
          <!-- START_SECTION:stats -->\
          **GitHub Stats (including private repositories):**\
          - Total Repositories: '"$((public_repos + total_repos))"'\
          - Public Repositories: '"$public_repos"'\
          - Private Repositories: '"$total_repos"'\
          - Followers: '"$followers"'\
          - Following: '"$following"'\
          <!-- END_SECTION:stats -->' README.md

      - name: Commit and Push Changes
        run: |
          git config user.name 'GitHub Actions Bot'
          git config user.email 'actions@github.com'
          git add README.md
          git commit -m "Update README with latest private stats" || exit 0
          git push
