name: Update README

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name 'GitHub Actions Bot'
          git config user.email 'actions@github.com'

      - name: Fetch latest changes
        run: |
          git fetch origin main

      - name: Update README
        run: |
          # Store existing content
          cp README.md README.md.bak
          
          # Update the stats section
          sed -n '/<!--START_SECTION:github_stats-->/,/<!--END_SECTION:github_stats-->/!p' README.md.bak > README.md
          echo "<!--START_SECTION:github_stats-->" >> README.md
          echo "![Timothy's GitHub Stats](https://github-readme-stats.vercel.app/api?username=itsanamune&show_icons=true&theme=radical)" >> README.md
          echo "![Top Languages](https://github-readme-stats.vercel.app/api/top-langs/?username=itsanamune&layout=compact&theme=radical)" >> README.md
          echo "![GitHub Streak](https://github-readme-streak-stats.herokuapp.com/?user=itsanamune&theme=radical)" >> README.md
          echo "![Trophies](https://github-profile-trophy.vercel.app/?username=itsanamune&theme=onedark&column=7)" >> README.md
          echo "<!--END_SECTION:github_stats-->" >> README.md
          
          # Append the rest of the content
          sed -n '/<!--END_SECTION:github_stats-->/,$p' README.md.bak >> README.md
          
          # Clean up
          rm README.md.bak

      - name: Commit and Push Changes
        run: |
          git add README.md
          git commit -m "Update README with latest stats" || exit 0
          git pull --rebase origin main
          git push
